name: Generate Chart

on:
  schedule:
    - cron: '0 16 * * *' 
  push:
    branches:
      - main 

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      TZ: 'Australia/Perth'
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install PyGithub matplotlib pytz

      - name: Generate Chart
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python chart/scripts/generate_chart.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "gh-actions-bot@example.com"
          git config pull.rebase false  
          git config pull.ff only    

      - name: Commit and push
        run: |
          git add .
          if git diff --exit-code --staged; then
            echo "No changes to commit. Exiting."
            exit 0
          else
            git commit -m "Updated Chart - $(date)"
            git pull origin main --ff-only 
            git push
          fi
