name: Generate Chart

on:
  schedule:
    - cron: '0 16 * * *' 
  push:
    branches:
      - main 

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: 'Australia/Perth'
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install PyGithub matplotlib pytz

      - name: Generate Chart
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python chart/scripts/generate_chart.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "gh-actions-bot@example.com"

      - name: Commit and push
        run: |
          git add README.md chart.png
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "📈 Update GitHub Stats - $(date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin main
          git push origin main
