name: Generate Chart

on:
  schedule:
  # cron to run every 2 minutes
    - cron:  '*/2 * * * *'
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      TZ: 'Australia/Perth'
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install PyGithub matplotlib
      
    - name: Generate Chart
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python chart/scripts/generate_chart.py
      
    - name: Commit and push
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "www.gh-personalreadme-chart-worker.bot"
        git add .
        git commit -m "Updated Chart - $(date)"
        git push
