name: Update GitHub Stats

on:
  schedule:
    - cron: '0 16 * * *' 
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      TZ: 'Australia/Perth'
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install PyGithub requests pytz

      - name: Generate README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python scripts/generate.py 

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "gh-actions-bot@example.com"

      - name: Commit and push changes
        run: |
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "📈 Update GitHub Stats - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
