name: Generate Language Chart

on:
  schedule:
    - cron:  '0 0 * * *' # Runs every day at midnight
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install PyGithub matplotlib
      
    - name: Generate Chart
      run: python generate_chart.py
      
    - name: Commit and push
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<your_email>"
        git add .
        git commit -m "Updated chart"
        git push
